### ISSUE TITLE
是代码缺失还是其它的编译方式？

### ISSUE THREAD

**Issue by sbdwtg00** [justlive1/baiduTongJi#1]
为什么代码没有构造器参数和set，get方法

**Comment by justlive1** [comment]
用的是lombok插件生成getter和setter

**Comment by sbdwtg00** [comment]
我没有用这个插件生成setter和getter，但是他们在代码里是没有的。
同时另外一个问题，百度统计的api接口已经发生了一些改变




在 2017-04-18 09:58:43，"justlive1" <notifications@github.com> 写道：


用的是lombok插件生成getter和setter
